import "server-only";

import type { DraftGenerator, DraftGeneratorInput } from "@/lib/ai/types";
import { getServerEnv } from "@/lib/config/server";
import { AppError } from "@/lib/errors/app-error";
import { getOpenAIClient } from "@/lib/openai/client";
import { mapOpenAIError } from "@/lib/openai/error";
import { listingDraftSchema, type ListingDraft } from "@/lib/validation/listing-session";
import { SANITY_LOCALES, type SanityLocale } from "@/lib/validation/property-i18n";

// OpenAI strict mode requires ALL properties to be listed in `required`.
// Locale fields are always expected — the model must fill all 5 or copy EN.
const localeShape = {
  type: "object",
  additionalProperties: false,
  required: ["en", "uk", "ru", "sq", "it"],
  properties: {
    en: { type: "string" },
    uk: { type: "string" },
    ru: { type: "string" },
    sq: { type: "string" },
    it: { type: "string" },
  },
} as const;

// OpenAI strict mode rules:
//   1. ALL properties in `properties` MUST appear in `required` — no exceptions.
//   2. ALL objects must have `additionalProperties: false`.
//   3. "Optional" fields are expressed as nullable: { type: ["string", "null"] }.
//   4. rawExtractedFacts is injected by the service after generation — not generated by the model.
const listingDraftJsonSchema = {
  name: "listing_draft",
  strict: true,
  schema: {
    type: "object",
    additionalProperties: false,
    required: [
      "internalRef", "status", "title", "slug", "shortDescription", "description",
      "price", "dealStatus", "facts", "address",
      "sanityCityRef", "sanityDistrictRef", "sanityPropertyTypeRef", "sanityAgentRef",
      "amenities", "locationTags", "propertyOffers", "seo", "ai", "sourceSessionId",
    ],
    properties: {
      internalRef: { type: ["string", "null"] },
      status: { type: "string", enum: ["draft", "in_review", "published", "archived"] },
      title: { ...localeShape },
      slug: {
        type: "object",
        additionalProperties: false,
        required: ["current"],
        properties: { current: { type: "string" } },
      },
      shortDescription: { ...localeShape },
      description: { ...localeShape },
      price: { type: ["number", "null"] },
      dealStatus: { type: "string", enum: ["sale", "rent", "short-term"] },
      facts: {
        type: "object",
        additionalProperties: false,
        // All properties required; optional ones are nullable
        required: ["propertyType", "area", "bedrooms", "bathrooms", "yearBuilt"],
        properties: {
          propertyType: { type: "string" },
          area: { type: "number" },
          bedrooms: { type: ["number", "null"] },
          bathrooms: { type: ["number", "null"] },
          yearBuilt: { type: ["number", "null"] },
        },
      },
      address: {
        type: "object",
        additionalProperties: false,
        required: ["countryCode", "city", "district", "streetLine", "postalCode", "displayAddress", "hideExactLocation"],
        properties: {
          countryCode: { type: ["string", "null"] },
          city: { type: ["string", "null"] },
          district: { type: ["string", "null"] },
          streetLine: { type: ["string", "null"] },
          postalCode: { type: ["string", "null"] },
          displayAddress: { ...localeShape },
          hideExactLocation: { type: "boolean" },
        },
      },
      sanityCityRef: { type: ["string", "null"] },
      sanityDistrictRef: { type: ["string", "null"] },
      sanityPropertyTypeRef: { type: ["string", "null"] },
      sanityAgentRef: { type: ["string", "null"] },
      amenities: {
        type: "array",
        items: {
          type: "object",
          additionalProperties: false,
          required: ["_type", "_ref", "_weak"],
          properties: {
            _type: { type: "string", enum: ["reference"] },
            _ref: { type: "string" },
            _weak: { type: ["boolean", "null"] },
          },
        },
      },
      locationTags: {
        type: "array",
        items: {
          type: "object",
          additionalProperties: false,
          required: ["_type", "_ref", "_weak"],
          properties: {
            _type: { type: "string", enum: ["reference"] },
            _ref: { type: "string" },
            _weak: { type: ["boolean", "null"] },
          },
        },
      },
      propertyOffers: {
        type: "array",
        items: {
          type: "object",
          additionalProperties: false,
          required: ["title", "iconKey"],
          properties: {
            title: { ...localeShape },
            iconKey: { type: ["string", "null"] },
          },
        },
      },
      seo: {
        type: "object",
        additionalProperties: false,
        required: ["metaTitle", "metaDescription", "canonicalUrl", "noIndex"],
        properties: {
          metaTitle: { ...localeShape },
          metaDescription: { ...localeShape },
          canonicalUrl: { type: ["string", "null"] },
          noIndex: { type: ["boolean", "null"] },
        },
      },
      // rawExtractedFacts is injected by the service after generation — not from the model.
      ai: {
        type: "object",
        additionalProperties: false,
        required: ["provider", "model", "confidence", "warnings"],
        properties: {
          provider: { type: "string" },
          model: { type: "string" },
          confidence: { type: ["number", "null"] },
          warnings: { type: "array", items: { type: "string" } },
        },
      },
      sourceSessionId: { type: ["string", "null"] },
    },
  },
} as const;

function buildPrompt(input: DraftGeneratorInput) {
  const emphasizedLocale = input.languageContext?.emphasizedLocale;
  const langNote = emphasizedLocale && emphasizedLocale !== "en"
    ? `The realtor wrote primarily in ${emphasizedLocale === "ru" ? "Russian" : emphasizedLocale === "uk" ? "Ukrainian" : emphasizedLocale === "sq" ? "Albanian" : "Italian"}. The ${emphasizedLocale} locale should feel especially natural and idiomatic.`
    : "";

  const briefNote = input.contentBrief?.trim()
    ? `\nCONTENT BRIEF (apply to description tone/audience):\n${input.contentBrief.trim()}`
    : "";

  const visualContextNote = input.visualContext?.trim()
    ? `\n${input.visualContext.trim()}`
    : "";

  const styleExampleNote = input.descriptionStyleExample?.trim()
    ? [
        "",
        "STYLE TEMPLATE — MANDATORY:",
        "An operator has provided the following example description as a STYLE REFERENCE.",
        "You MUST:",
        "  • Mimic the example's tone, paragraph structure, formatting, spacing, emoji usage, and sales style.",
        "  • Apply this style to ALL generated locales (en, uk, ru, sq, it) adapted naturally to each language.",
        "You MUST NOT:",
        "  • Copy any factual content from the example (price, city, size, address, property type, etc.).",
        "  • Invent facts to match the example — all facts come from extractedFacts below.",
        "  • Use the example as a content source — it is a STYLE SOURCE ONLY.",
        "---STYLE EXAMPLE BEGIN---",
        input.descriptionStyleExample.trim(),
        "---STYLE EXAMPLE END---",
      ].join("\n")
    : "";

  return [
    "You are a senior real-estate editorial assistant producing professional listing content.",
    "Generate a single JSON object ONLY; no markdown, no prose, no code fences.",
    "",
    "Trust hierarchy:",
    "1) extractedFacts — canonical source for all hard facts (price, area, city, propertyType, dealStatus, bedrooms, bathrooms).",
    "2) sourceText and transcript — narrative context, tone, selling points.",
    "3) STYLE TEMPLATE (if present) — style/format/emoji reference ONLY; never a fact source.",
    "4) Do not invent hard facts. Omit if genuinely unknown.",
    langNote,
    briefNote,
    visualContextNote,
    styleExampleNote,
    "",
    "LOCALIZATION — MANDATORY:",
    "ALL localized string fields (title, shortDescription, description, address.displayAddress,",
    "seo.metaTitle, seo.metaDescription, every propertyOffers[].title) MUST be populated in ALL 5 locales: en, uk, ru, sq, it.",
    "CRITICAL: Generate each locale DIRECTLY in its target language. Do NOT write EN first and translate.",
    "  • en  — write the full description naturally in English.",
    "  • ru  — write DIRECTLY in Russian as a native Russian-speaking realtor would. Do NOT translate from EN.",
    "  • uk  — write DIRECTLY in Ukrainian. Do NOT translate from EN or RU.",
    "  • sq  — write DIRECTLY in Albanian using local real-estate phrasing.",
    "  • it  — write DIRECTLY in Italian using Italian property market conventions.",
    "If a STYLE TEMPLATE is provided, apply its emoji usage, paragraph rhythm and sales energy independently",
    "to each locale — adapt phrasing to each language's natural style, never copy the EN wording.",
    "",
    "CONTENT QUALITY:",
    "- title: concise, appealing (max ~60 chars per locale). Include property type, city, key feature.",
    "- shortDescription: 1-2 sentences, highlights the most compelling selling points.",
    "- description: 2-4 paragraphs. Start with a strong hook. Cover: location & neighbourhood, property",
    "  features, lifestyle benefits. Write in present tense, active voice. Be specific, not generic.",
    "  If contentBrief specifies an audience (investor, family, etc.), tailor description accordingly.",
    "  Each locale MUST be written directly in its target language, not translated from EN.",
    "  Incorporate any VISUAL SIGNALS (if present) naturally into every locale.",
    "- propertyOffers: 3-6 items, each highlighting a distinct selling point with a localized title.",
    "- seo: metaTitle concise (≤60 chars), metaDescription compelling summary (≤155 chars).",
    "",
    "Hard rules:",
    "- price is EUR only — a single number, not a currency object.",
    "- dealStatus must be exactly: sale, rent, or short-term.",
    "- facts.area is m² only — do NOT add bedrooms/elevator/furnished/parking/energyClass as fact scalars.",
    "- gallery and coverImage MUST be absent — they are filled from uploaded assets.",
    "- Use only canonical cities/propertyTypes from REFERENCE_DATA. If no match, leave unset.",
    "- iconKey for propertyOffers must come from the ICON_KEYS list in REFERENCE_DATA or be omitted.",
    "- shortDescription MUST be output (it is required in the schema).",
    "",
    input.referenceContextText?.trim()
      ? ["--- REFERENCE_DATA ---", input.referenceContextText.trim(), "--- END REFERENCE_DATA ---", ""].join("\n")
      : "",
    `sourceText:\n${input.sourceText || "(empty)"}`,
    "",
    `transcript:\n${input.transcript || "(empty)"}`,
    "",
    `extractedFacts:\n${JSON.stringify(input.extractedFacts)}`,
  ].join("\n");
}

/**
 * Recursively remove null values from the AI output so Zod sees `undefined`
 * for absent optional fields (Zod schemas use `optional()`, not `nullable()`).
 * The OpenAI strict schema uses nullable types to satisfy "all properties in required",
 * but our Zod validation expects missing keys rather than explicit nulls.
 */
function stripNullsDeep(value: unknown): unknown {
  if (value === null) return undefined;
  if (Array.isArray(value)) return value.map(stripNullsDeep).filter((v) => v !== undefined);
  if (value && typeof value === "object") {
    return Object.fromEntries(
      Object.entries(value as Record<string, unknown>)
        .map(([k, v]) => [k, stripNullsDeep(v)])
        .filter(([, v]) => v !== undefined),
    );
  }
  return value;
}

/**
 * Sanitize a locale object by converting empty or whitespace-only strings to absent keys.
 *
 * WHY THIS EXISTS:
 * OpenAI strict mode requires all 5 locale keys to be `type: "string"`. The model
 * satisfies this by returning `""` for locales it cannot fill rather than null.
 * Our Zod `localizedStringSchema` uses `z.string().min(1).optional()` — a present
 * empty string `""` passes the type check but fails `min(1)`, throwing a ZodError.
 * By dropping empty strings here (before Zod), `.optional()` then applies correctly
 * and `ensureLocaleCompleteness` fills the gaps with EN content downstream.
 */
function sanitizeLocaleObject(obj: unknown): Record<string, string> | undefined {
  if (!obj || typeof obj !== "object" || Array.isArray(obj)) return undefined;
  const result: Record<string, string> = {};
  for (const [k, v] of Object.entries(obj as Record<string, unknown>)) {
    if (typeof v === "string" && v.trim()) {
      result[k] = v.trim();
    }
  }
  return Object.keys(result).length > 0 ? result : undefined;
}

function missingLocalesFor(value: Partial<Record<SanityLocale, string | undefined>> | undefined): SanityLocale[] {
  return SANITY_LOCALES.filter((locale) => !(value?.[locale] ?? "").trim());
}

function ensureLocaleCompleteness(
  field: Partial<Record<SanityLocale, string | undefined>> | undefined,
  fieldName: "title" | "shortDescription" | "description",
): Record<SanityLocale, string> {
  const en = (field?.en ?? "").trim();
  const next: Record<SanityLocale, string> = {
    en,
    uk: (field?.uk ?? "").trim(),
    ru: (field?.ru ?? "").trim(),
    sq: (field?.sq ?? "").trim(),
    it: (field?.it ?? "").trim(),
  };
  for (const locale of SANITY_LOCALES) {
    if (!next[locale] && en) {
      next[locale] = en;
    }
  }
  const stillMissing = SANITY_LOCALES.filter((locale) => !next[locale]);
  if (stillMissing.length > 0) {
    console.warn(`[ai][draft] ${fieldName} has empty locales after repair`, stillMissing);
  }
  return next;
}

const localizedContentRepairSchema = {
  name: "localized_content_repair",
  strict: true,
  schema: {
    type: "object",
    additionalProperties: false,
    required: ["title", "shortDescription", "description"],
    properties: {
      title: { ...localeShape },
      shortDescription: { ...localeShape },
      description: { ...localeShape },
    },
  },
} as const;

async function repairMissingLocalizedContent(params: {
  client: ReturnType<typeof getOpenAIClient>;
  model: string;
  input: DraftGeneratorInput;
  draft: ListingDraft;
}): Promise<ListingDraft> {
  const { client, model, input, draft } = params;
  const missing = {
    title: missingLocalesFor(draft.title),
    shortDescription: missingLocalesFor(draft.shortDescription),
    description: missingLocalesFor(draft.description),
  };
  const hasMissing = Object.values(missing).some((arr) => arr.length > 0);
  if (!hasMissing) return draft;

  console.info("[ai][draft] repairing missing locales", JSON.stringify(missing));

  const response = await client.responses.create({
    model,
    input: [
      {
        role: "user",
        content: [
          {
            type: "input_text",
            text: [
              "Fill missing locales for listing content.",
              "Return JSON only with full locale objects for title, shortDescription, description.",
              "Locales are mandatory: en, uk, ru, sq, it.",
              "Keep existing non-empty values semantically aligned. Fill only missing locales with natural translations.",
              "",
              `MISSING_LOCALES: ${JSON.stringify(missing)}`,
              `CURRENT_VALUES: ${JSON.stringify({
                title: draft.title,
                shortDescription: draft.shortDescription,
                description: draft.description,
              })}`,
              `FACTS_CONTEXT: ${JSON.stringify(input.extractedFacts)}`,
              `SOURCE_CONTEXT: ${input.sourceText || ""}\n${input.transcript || ""}`,
            ].join("\n"),
          },
        ],
      },
    ],
    text: {
      format: {
        type: "json_schema",
        ...localizedContentRepairSchema,
      },
    },
  });

  const outputText = response.output_text?.trim();
  if (!outputText) return draft;
  const rawRepaired = JSON.parse(outputText) as Record<string, unknown>;
  // Sanitize locale fields from repair model for the same reason as the main pass:
  // empty strings satisfy type:"string" in OpenAI strict schema but fail z.string().min(1).
  const repaired = stripNullsDeep({
    title: sanitizeLocaleObject(rawRepaired.title) ?? rawRepaired.title,
    shortDescription: sanitizeLocaleObject(rawRepaired.shortDescription) ?? rawRepaired.shortDescription,
    description: sanitizeLocaleObject(rawRepaired.description) ?? rawRepaired.description,
  }) as {
    title?: Partial<Record<SanityLocale, string>>;
    shortDescription?: Partial<Record<SanityLocale, string>>;
    description?: Partial<Record<SanityLocale, string>>;
  };

  return listingDraftSchema.parse({
    ...draft,
    title: { ...draft.title, ...(repaired.title ?? {}) },
    shortDescription: { ...draft.shortDescription, ...(repaired.shortDescription ?? {}) },
    description: { ...draft.description, ...(repaired.description ?? {}) },
  });
}

export class OpenAIDraftGenerator implements DraftGenerator {
  async generate(input: DraftGeneratorInput): Promise<ListingDraft> {
    try {
      console.log('STYLE EXAMPLE USED:', input.descriptionStyleExample ?? null);
      const env = getServerEnv();
      const client = getOpenAIClient();

      const response = await client.responses.create({
        model: env.OPENAI_DRAFT_MODEL,
        input: [
          {
            role: "user",
            content: [{ type: "input_text", text: buildPrompt(input) }],
          },
        ],
        text: {
          format: {
            type: "json_schema",
            ...listingDraftJsonSchema,
          },
        },
      });

      const outputText = response.output_text?.trim();
      if (!outputText) {
        throw new AppError("EXTERNAL_PROVIDER_FAILURE", "OpenAI draft generation returned empty output", 502);
      }

      console.info(
        "[ai][draft] response",
        JSON.stringify({
          stage: "draft",
          model: env.OPENAI_DRAFT_MODEL,
          requestId: response.id ?? null,
          outputChars: outputText.length,
        }),
      );

      const rawParsed = JSON.parse(outputText) as Record<string, unknown>;
      // Sanitize locale objects before stripNullsDeep: the model satisfies
      // `type: "string"` with "" for unknown locales, but localizedStringSchema
      // uses z.string().min(1).optional() — an empty string present in the object
      // is NOT treated as optional and throws ZodError. Removing empty strings
      // here lets .optional() apply and allows ensureLocaleCompleteness to fill gaps.
      const sanitizedTitle = sanitizeLocaleObject(rawParsed.title);
      const sanitizedShort = sanitizeLocaleObject(rawParsed.shortDescription);
      const sanitizedDesc = sanitizeLocaleObject(rawParsed.description);
      const localeEmptiesFound =
        (sanitizedTitle ? Object.keys(sanitizedTitle).length : 0) <
          (rawParsed.title && typeof rawParsed.title === "object" ? Object.keys(rawParsed.title).length : 0) ||
        (sanitizedShort ? Object.keys(sanitizedShort).length : 0) <
          (rawParsed.shortDescription && typeof rawParsed.shortDescription === "object"
            ? Object.keys(rawParsed.shortDescription).length
            : 0) ||
        (sanitizedDesc ? Object.keys(sanitizedDesc).length : 0) <
          (rawParsed.description && typeof rawParsed.description === "object"
            ? Object.keys(rawParsed.description).length
            : 0);
      if (localeEmptiesFound) {
        console.warn(
          "[ai][draft] sanitizeLocaleObject removed empty locale strings from model output",
          JSON.stringify({
            titleLocalesKept: Object.keys(sanitizedTitle ?? {}),
            shortDescLocalesKept: Object.keys(sanitizedShort ?? {}),
            descLocalesKept: Object.keys(sanitizedDesc ?? {}),
          }),
        );
      }
      const sanitized: Record<string, unknown> = {
        ...rawParsed,
        title: sanitizedTitle ?? rawParsed.title,
        shortDescription: sanitizedShort ?? rawParsed.shortDescription,
        description: sanitizedDesc ?? rawParsed.description,
      };
      const parsed = stripNullsDeep(sanitized);
      const validated = listingDraftSchema.parse(parsed);
      const repaired = await repairMissingLocalizedContent({
        client,
        model: env.OPENAI_DRAFT_MODEL,
        input,
        draft: validated,
      });
      const completed = listingDraftSchema.parse({
        ...repaired,
        title: ensureLocaleCompleteness(repaired.title, "title"),
        shortDescription: ensureLocaleCompleteness(repaired.shortDescription, "shortDescription"),
        description: ensureLocaleCompleteness(repaired.description, "description"),
      });
      console.info(
        "[ai][draft] parsed",
        JSON.stringify({
          stage: "draft",
          titlePresent: Boolean(completed.title?.en),
          shortDescriptionPresent: Boolean(completed.shortDescription?.en),
          cityPresent: Boolean(completed.address?.city),
          factsKeys: Object.keys(completed.facts ?? {}),
          localesWithTitle: Object.entries(completed.title ?? {})
            .filter(([, v]) => Boolean(v))
            .map(([k]) => k),
        }),
      );
      return completed;
    } catch (error) {
      console.error("[openai-draft-generator] generation failed");
      throw mapOpenAIError(error, "openai draft generation");
    }
  }
}
