import "server-only";

import type { DraftGenerator, DraftGeneratorInput } from "@/lib/ai/types";
import { getServerEnv } from "@/lib/config/server";
import { AppError } from "@/lib/errors/app-error";
import { getOpenAIClient } from "@/lib/openai/client";
import { mapOpenAIError } from "@/lib/openai/error";
import { listingDraftSchema, type ListingDraft } from "@/lib/validation/listing-session";

// OpenAI strict mode requires ALL properties to be listed in `required`.
// Locale fields are always expected — the model must fill all 5 or copy EN.
const localeShape = {
  type: "object",
  additionalProperties: false,
  required: ["en", "uk", "ru", "sq", "it"],
  properties: {
    en: { type: "string" },
    uk: { type: "string" },
    ru: { type: "string" },
    sq: { type: "string" },
    it: { type: "string" },
  },
} as const;

// OpenAI strict mode rules:
//   1. ALL properties in `properties` MUST appear in `required` — no exceptions.
//   2. ALL objects must have `additionalProperties: false`.
//   3. "Optional" fields are expressed as nullable: { type: ["string", "null"] }.
//   4. rawExtractedFacts is injected by the service after generation — not generated by the model.
const listingDraftJsonSchema = {
  name: "listing_draft",
  strict: true,
  schema: {
    type: "object",
    additionalProperties: false,
    required: [
      "internalRef", "status", "title", "slug", "shortDescription", "description",
      "price", "dealStatus", "facts", "address",
      "sanityCityRef", "sanityDistrictRef", "sanityPropertyTypeRef", "sanityAgentRef",
      "amenities", "locationTags", "propertyOffers", "seo", "ai", "sourceSessionId",
    ],
    properties: {
      internalRef: { type: ["string", "null"] },
      status: { type: "string", enum: ["draft", "in_review", "published", "archived"] },
      title: { ...localeShape },
      slug: {
        type: "object",
        additionalProperties: false,
        required: ["current"],
        properties: { current: { type: "string" } },
      },
      shortDescription: { ...localeShape },
      description: { ...localeShape },
      price: { type: ["number", "null"] },
      dealStatus: { type: "string", enum: ["sale", "rent", "short-term"] },
      facts: {
        type: "object",
        additionalProperties: false,
        // All properties required; optional ones are nullable
        required: ["propertyType", "area", "bedrooms", "bathrooms", "yearBuilt"],
        properties: {
          propertyType: { type: "string" },
          area: { type: "number" },
          bedrooms: { type: ["number", "null"] },
          bathrooms: { type: ["number", "null"] },
          yearBuilt: { type: ["number", "null"] },
        },
      },
      address: {
        type: "object",
        additionalProperties: false,
        required: ["countryCode", "city", "district", "streetLine", "postalCode", "displayAddress", "hideExactLocation"],
        properties: {
          countryCode: { type: ["string", "null"] },
          city: { type: ["string", "null"] },
          district: { type: ["string", "null"] },
          streetLine: { type: ["string", "null"] },
          postalCode: { type: ["string", "null"] },
          displayAddress: { ...localeShape },
          hideExactLocation: { type: "boolean" },
        },
      },
      sanityCityRef: { type: ["string", "null"] },
      sanityDistrictRef: { type: ["string", "null"] },
      sanityPropertyTypeRef: { type: ["string", "null"] },
      sanityAgentRef: { type: ["string", "null"] },
      amenities: {
        type: "array",
        items: {
          type: "object",
          additionalProperties: false,
          required: ["_type", "_ref", "_weak"],
          properties: {
            _type: { type: "string", enum: ["reference"] },
            _ref: { type: "string" },
            _weak: { type: ["boolean", "null"] },
          },
        },
      },
      locationTags: {
        type: "array",
        items: {
          type: "object",
          additionalProperties: false,
          required: ["_type", "_ref", "_weak"],
          properties: {
            _type: { type: "string", enum: ["reference"] },
            _ref: { type: "string" },
            _weak: { type: ["boolean", "null"] },
          },
        },
      },
      propertyOffers: {
        type: "array",
        items: {
          type: "object",
          additionalProperties: false,
          required: ["title", "iconKey"],
          properties: {
            title: { ...localeShape },
            iconKey: { type: ["string", "null"] },
          },
        },
      },
      seo: {
        type: "object",
        additionalProperties: false,
        required: ["metaTitle", "metaDescription", "canonicalUrl", "noIndex"],
        properties: {
          metaTitle: { ...localeShape },
          metaDescription: { ...localeShape },
          canonicalUrl: { type: ["string", "null"] },
          noIndex: { type: ["boolean", "null"] },
        },
      },
      // rawExtractedFacts is injected by the service after generation — not from the model.
      ai: {
        type: "object",
        additionalProperties: false,
        required: ["provider", "model", "confidence", "warnings"],
        properties: {
          provider: { type: "string" },
          model: { type: "string" },
          confidence: { type: ["number", "null"] },
          warnings: { type: "array", items: { type: "string" } },
        },
      },
      sourceSessionId: { type: ["string", "null"] },
    },
  },
} as const;

function buildPrompt(input: DraftGeneratorInput) {
  return [
    "You are a senior real-estate editorial assistant producing professional listing content.",
    "Generate a single JSON object ONLY; no markdown, no prose, no code fences.",
    "",
    "Trust hierarchy:",
    "1) extractedFacts — canonical source for all hard facts (price, area, city, propertyType, dealStatus, bedrooms, bathrooms).",
    "2) sourceText and transcript — narrative context, tone, selling points.",
    "3) Do not invent hard facts. Omit if genuinely unknown.",
    "",
    "LOCALIZATION — MANDATORY:",
    "ALL localized string fields (title, shortDescription, description, address.displayAddress,",
    "seo.metaTitle, seo.metaDescription, every propertyOffers[].title) MUST be populated in ALL 5 locales: en, uk, ru, sq, it.",
    "Translate meaningfully — do not just repeat the EN string. Use natural phrasing for each language.",
    "For Albanian (sq) and Italian (it), use proper real-estate terminology for that market.",
    "",
    "CONTENT QUALITY:",
    "- title: concise, appealing (max ~60 chars per locale). Include property type, city, key feature.",
    "- shortDescription: 1-2 sentences, highlights the most compelling selling points.",
    "- description: 2-4 paragraphs. Start with a strong hook. Cover: location & neighbourhood, property",
    "  features, lifestyle benefits. Write in present tense, active voice. Be specific, not generic.",
    "- propertyOffers: 3-6 items, each highlighting a distinct selling point with a localized title.",
    "- seo: metaTitle concise (≤60 chars), metaDescription compelling summary (≤155 chars).",
    "",
    "Hard rules:",
    "- price is EUR only — a single number, not a currency object.",
    "- dealStatus must be exactly: sale, rent, or short-term.",
    "- facts.area is m² only — do NOT add bedrooms/elevator/furnished/parking/energyClass as fact scalars.",
    "- gallery and coverImage MUST be absent — they are filled from uploaded assets.",
    "- Use only canonical cities/propertyTypes from REFERENCE_DATA. If no match, leave unset.",
    "- iconKey for propertyOffers must come from the ICON_KEYS list in REFERENCE_DATA or be omitted.",
    "- shortDescription MUST be output (it is required in the schema).",
    "",
    input.referenceContextText?.trim()
      ? ["--- REFERENCE_DATA ---", input.referenceContextText.trim(), "--- END REFERENCE_DATA ---", ""].join("\n")
      : "",
    `sourceText:\n${input.sourceText || "(empty)"}`,
    "",
    `transcript:\n${input.transcript || "(empty)"}`,
    "",
    `extractedFacts:\n${JSON.stringify(input.extractedFacts)}`,
  ].join("\n");
}

/**
 * Recursively remove null values from the AI output so Zod sees `undefined`
 * for absent optional fields (Zod schemas use `optional()`, not `nullable()`).
 * The OpenAI strict schema uses nullable types to satisfy "all properties in required",
 * but our Zod validation expects missing keys rather than explicit nulls.
 */
function stripNullsDeep(value: unknown): unknown {
  if (value === null) return undefined;
  if (Array.isArray(value)) return value.map(stripNullsDeep).filter((v) => v !== undefined);
  if (value && typeof value === "object") {
    return Object.fromEntries(
      Object.entries(value as Record<string, unknown>)
        .map(([k, v]) => [k, stripNullsDeep(v)])
        .filter(([, v]) => v !== undefined),
    );
  }
  return value;
}

export class OpenAIDraftGenerator implements DraftGenerator {
  async generate(input: DraftGeneratorInput): Promise<ListingDraft> {
    try {
      const env = getServerEnv();
      const client = getOpenAIClient();

      const response = await client.responses.create({
        model: env.OPENAI_DRAFT_MODEL,
        input: [
          {
            role: "user",
            content: [{ type: "input_text", text: buildPrompt(input) }],
          },
        ],
        text: {
          format: {
            type: "json_schema",
            ...listingDraftJsonSchema,
          },
        },
      });

      const outputText = response.output_text?.trim();
      if (!outputText) {
        throw new AppError("EXTERNAL_PROVIDER_FAILURE", "OpenAI draft generation returned empty output", 502);
      }

      console.info(
        "[ai][draft] response",
        JSON.stringify({
          stage: "draft",
          model: env.OPENAI_DRAFT_MODEL,
          requestId: response.id ?? null,
          outputChars: outputText.length,
        }),
      );

      const parsed = stripNullsDeep(JSON.parse(outputText));
      const validated = listingDraftSchema.parse(parsed);
      console.info(
        "[ai][draft] parsed",
        JSON.stringify({
          stage: "draft",
          titlePresent: Boolean(validated.title?.en),
          shortDescriptionPresent: Boolean(validated.shortDescription?.en),
          cityPresent: Boolean(validated.address?.city),
          factsKeys: Object.keys(validated.facts ?? {}),
          localesWithTitle: Object.entries(validated.title ?? {})
            .filter(([, v]) => Boolean(v))
            .map(([k]) => k),
        }),
      );
      return validated;
    } catch (error) {
      console.error("[openai-draft-generator] generation failed");
      throw mapOpenAIError(error, "openai draft generation");
    }
  }
}
